# Generated by Django 5.1.5 on 2025-02-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_service_description_en_service_description_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ar',
            field=models.CharField(max_length=99, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=99, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=99, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('1', 'Веб разработка'), ('2', 'Дизайн'), ('3', 'Маркетинг'), ('4', 'Копирайтинг'), ('5', 'Рерайтинг'), ('6', 'Видеомонтаж'), ('7', 'Фотошоп')], default='1', max_length=1, verbose_name='Тип услуги'),
        ),
    ]
