# Generated by Django 5.1.5 on 2025-02-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_executor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_ar',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_en',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1, max_length=1, null=True),
        ),
    ]
