# Generated by Django 5.1.5 on 2025-02-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_review_description_ar_review_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description_ar',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating_ar',
            new_name='rating_ru',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description_ar',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name_ar',
            new_name='name_ru',
        ),
    ]
